### ISSUE TITLE
Use gender-neutral term to describe the core team

### ISSUE THREAD

**Issue by interstateone** [rails/rails.github.com#14]
I ran across the core team page the other day and noticed the phrase "made men" in the [header](https://github.com/rails/rails.github.com/blob/master/images/headers/core.gif). Although the list does seem to be all men right now it seems a bit (accidentally, I'm sure) presumptuous to use the phrase. I wonder if there is another phrase that has similar connotations of loyalty and hard work that doesn't specify gender?

I don't have a specific suggestion for what that phrase should be (beyond searching the thesaurus for "hard-working") but I'm hoping that it can be narrowed down here and am willing to help.

I'll also note that the header containing the phrase is a raster image and the source file doesn't appear to be in this repo.

I hope that this can kick off a good conversation. :smile:

**Comment by claudiob** [comment]
> As soon as the TypeKit website is back up I'll add Light to the font bundle and you can use the web inspector to play around with it.

@pixeltrix has this happened? Let me know :grin:

**Comment by pixeltrix** [comment]
@claudiob it has now :smile:

**Comment by pixeltrix** [comment]
@claudiob can we close this?

**Comment by claudiob** [comment]
@pixeltrix Yes, go ahead and close it. I'm not an admin on this project… :wink:
