### ISSUE TITLE
Updating the 'Rails x.y.z has been released!' on homepage

### ISSUE THREAD

**Issue by cllns** [rails/rails.github.com#30]
It's a bother to manually update this repo to link to the latest 'Release' blog post.

Two options I see:
- Populating this text via JS, by reading from and parsing http://weblog.rubyonrails.org/feed/atom.xml

- Merging **rails/rails.github.com** and **rails/weblog** into one repo. Then we could just pull it the latest blog post programmatically. They both use jekyll, so it wouldn't be *too* hard.

I'm open to helping with either.

**Comment by jankeesvw** [comment]
Merging the two repo's sounds like good plan to me.

**Comment by rafaelfranca** [comment]
I think it is better to just remove the links

**Comment by rafaelfranca** [comment]
That link was removed, so closing this one.
