### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by claudiob** [rails/rails.github.com#46]
Hello!

I would like to know how do you feel about making the website responsive to different browser widths.

---

Currently, this is how the [Rails Core page](http://rubyonrails.org/core) looks when a Safari window is stretched, and on an iPhone:

![before-safari](https://cloud.githubusercontent.com/assets/10076/7447018/60dda602-f1a0-11e4-925c-b1dc940324a6.png)
![before-iphone](https://cloud.githubusercontent.com/assets/10076/7447017/60dbcb66-f1a0-11e4-80e1-885c5dcfd354.png)

---

I've spent a couple of hours to change the HTML/CSS code so that the page would look exactly the same at a normal browser resolution, but would adapt nicely to a smaller resolution:

![after-safari](https://cloud.githubusercontent.com/assets/10076/7447027/aa11e252-f1a0-11e4-9ba1-5c907daafd1b.png)
![after-iphone](https://cloud.githubusercontent.com/assets/10076/7447026/aa0ef2e0-f1a0-11e4-8d8c-b41929082ef3.png)

---

Before I create a full pull request, which would make all the pages responsive, I would like to know if you have anything against this change. My concern is not about the actual HTML/CSS code (we can discuss about that), but more if you think that this would be a good overall change.

I invite you to try the final result by yourself by pointing your browser to:

* responsive "Core" page: http://claudiob.github.io/rails.github.com/core
* responsive "Core Alumni" page: http://claudiob.github.io/rails.github.com/core/alumni

and comparing them with the current ones. Thanks :ribbon:

**Comment by rafaelfranca** [comment]
We were planing a redesign of the site but while we don't have that I'm :+1: for responsive pages.

**Comment by rafaelfranca** [comment]
cc @dhh

**Comment by claudiob** [comment]
@rafaelfranca My idea is that we can improve the layout of the current version while, on a separate note, we discuss all the complexities related to a full-revamp, such as changing the copy, the content, the links, the colors, and so on.

The goal of the PR would be to keep the site exactly as it is (content, color, copy, …) and only focus on making it more usable on smaller devices.

**Comment by rafaelfranca** [comment]
Seems good to me

**Comment by dhh** [comment]
👍 on going responsive!

**Comment by korabh** [comment]
@dhh @rafaelfranca I would gladly like to be part of the redesigning process. If yes, then how can i be part of this endvour.
