### ISSUE TITLE
New design for Rails 5?

### ISSUE THREAD

**Issue by cllns** [rails/rails.github.com#71]
The [rubyonrails.org](http://rubyonrails.org) homepage looks a little dated. It was last updated [nearly 10 years ago, for the release of Rails 1.0](https://web.archive.org/web/20051214180106/http://www.rubyonrails.org/).

It'd be nice to refresh the design for the Rails 5.0 release.

Maybe a company that relies Rails can donate time to make a new design? I'd be happy to help out, though I'm not a designer. (If someone provides a design, I'd be happy to implement in HTML and Sass with Middleman.)

Thoughts?

**Comment by cllns** [comment]
ping @dhh

**Comment by dhh** [comment]
I'm going to take a swing at this prior to the final 5.0 release. I'll reopen this thread in case I need assistance. Thanks for offering!
