### ISSUE TITLE
No link to rails 4.2.5

### ISSUE THREAD

**Issue by moorage** [rails/rails.github.com#74]
Even though it was released 13 days ago :)

**Comment by rafaelfranca** [comment]
Which link are you talking about?

**Comment by moorage** [comment]
https://github.com/rails/rails.github.com/blob/master/index.html#L23

Perhaps it's just the text

**Comment by rafaelfranca** [comment]
Yes, it is just text.

**Comment by rafaelfranca** [comment]
Done
